version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports: 
      - 3000:3000
    working_dir: /e2eCypressDockerExample
    volumes: 
      - ./:/e2eCypressDockerExample
    environment: 
      MYSQL_HOST: mysql 
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes: 
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - app
      - mysql
    environment:
      - CYPRESS_baseUrl=http://app:3000
    working_dir: /e2eCypressDockerExample/e2e
    volumes:
      - ./e2e/:/e2eCypressDockerExample/e2e

volumes:
  todo-mysql-data: